### ISSUE TITLE
INDUCCION

### ISSUE THREAD

**Issue by NBbrook** [SistemasTecTlaxiaco/actividad-9-practica-de-inducci-n-matem-tica-club-noobbaby#1]
[sprint 3 induccion.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-de-inducci-n-matem-tica-club-noobbaby/files/13246237/sprint.3.induccion.pdf)

**Comment by 23620031** [comment]
PORTADA 25/25
PROCEDIMIENTO 25/25
FIGURAS 25/25
RESULTADO Y CONCLUCIÓN 25/25 
_______________________________________________________________________________
CALIFICACIÓN TOTAL 20/20

CALIFICADO POR ISAÍAS Y EQUIPO

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
